routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'welcome');

Auth::routes(['register' => false]);

Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.', 'middleware' => ['auth']], function () {
    Route::redirect('/', '/dashboard/categories');
    Route::apiResource('categories', 'CategoryController')->except(['update']);
    Route::get('albums/categories', 'AlbumController@getByCategoryId')->name('albums.category');
    Route::apiResource('albums', 'AlbumController')->except(['update']);
    Route::post('images/regenerate/{albumId}', 'ImageController@regenerate')->name('images.regenerate');
    Route::apiResource('images', 'ImageController')->except(['update', 'show']);
});

app/Models/Category.php
<?php

namespace App\Models;

use App\Models\Album;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $guarded = [];

    public function albums()
    {
        return $this->hasMany(Album::class);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Repositories\CategoryRepositoryInterface;
use DataTables;
use Illuminate\Http\Request;
use Storage;

class CategoryController extends Controller
{
    private $categoryRepository;

    public function __construct(CategoryRepositoryInterface $categoryRepository)
    {
        $this->categoryRepository = $categoryRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if (! $request->ajax()) {
            return view('dashboard.category.index');
        }

        $categories = $this->categoryRepository->index();

        return DataTables::of($categories)->make(true);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'name' => 'required|unique:categories|regex:/^[A-Za-z0-9._\s-]+$/',
            'slug' => 'required|unique:categories|regex:/^[A-Za-z0-9-]+$/',
        ], [
            'regex' => 'Karakter yang diperbolehkan adalah a-z, A-Z, 0-9, titik (.), underscore (_), tanda pisah (-), dan spasi',
            'slug' => 'Karakter yang diperbolehkan adalah a-z, A-Z, 0-9, dan tanda pisah (-)',
            'unique' => 'Nama sudah ada'
        ]);

        return $this->categoryRepository->store($data);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = $this->categoryRepository->firstOrFail($id);

        return view('dashboard.category.show', compact('category'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = $this->categoryRepository->firstOrFail($id);
        $isDeleted = $this->categoryRepository->destroy($id);

        if ($isDeleted) {
            return Storage::deleteDirectory($category->slug);
        }
    }
}

resources/views/dashboard/category/index.blade.php
@extends('layouts.sbAdmin2.app')

@section('title', 'Categories')

@section('head')
    <script src="{{ mix('js/dashboard/category/index.js') }}" defer></script>
@endsection

@section('content')
<!-- Page Heading -->
<h1 class="h3 mb-4 text-gray-800">Categories</h1>
<div class="row mb-2">
    <div class="col text-right">
        <button class="btn btn-primary" data-toggle="modal" data-target="#kategori-tambah-modal">Add Category</button>
    </div>
</div>
<div class="row">
    <div class="col">
        <div class="card shadow mb-4">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Albums</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="kategori-tambah-modal" tabindex="-1" role="dialog" aria-labelledby="kategori-tambah-modal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <form class="needs-validation" novalidate>
            @csrf
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Tambah Kategori</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="kategori-tambah-nama">Nama</label>
                        <input type="text" class="form-control" id="kategori-tambah-nama" name="name" pattern="[A-Za-z0-9-_. ]+" required>
                        <small class="form-text text-muted">Karakter yang diperbolehkan adalah a-z, A-Z, 0-9, titik (.), underscore (_), tanda pisah (-), dan spasi</small>
                        <div class="invalid-feedback">
                            Data tidak boleh kosong
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="kategori-tambah-slug">Slug</label>
                        <input type="text" class="form-control" id="kategori-tambah-slug" name="slug" pattern="[A-Za-z0-9-]+" required>
                        <small class="form-text text-muted">Karakter yang diperbolehkan adalah a-z, A-Z, 0-9, dan tanda pisah (-)</small>
                        <div class="invalid-feedback">
                            Data tidak boleh kosong
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                    <button type="submit" class="btn btn-primary">Tambah</button>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="modal fade" id="kategori-hapus-modal" tabindex="-1" role="dialog" aria-labelledby="kategori-hapus-modal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <form class="needs-validation" novalidate>
            @csrf
            <input type="hidden" name="id" id="kategori-hapus-id">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Hapus Kategori</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>
                        Apakah Anda yakin akan menghapus kategori <strong></strong>?
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-danger">Hapus</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/dashboard/category/show.blade.php
@extends('layouts.sbAdmin2.app')

@section('title', $category->name)

@section('head')
    <meta name="category-id" content="{{ $category->id }}">
    <script src="{{ mix('js/dashboard/category/show.js') }}" defer></script>
@endsection

@section('content')
<!-- Page Heading -->
<h1 class="h3 mb-4 text-gray-800">{{ $category->name }}</h1>
<div class="row mb-2">
    <div class="col text-left">
        <a href="{{ route('dashboard.categories.index') }}" class="btn btn-secondary btn-icon-split">
            <span class="icon text-white-50">
                <i class="fas fa-arrow-left"></i>
            </span>
            <span class="text">Back</span>
        </a>
    </div>
    <div class="col text-right">
        <button class="btn btn-primary" data-toggle="modal" data-target="#album-tambah-modal">Add Album</button>
    </div>
</div>
<div class="row">
    <div class="col">
        <div class="card shadow mb-4">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Title</th>
                                <th>Images</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="album-tambah-modal" tabindex="-1" role="dialog" aria-labelledby="album-tambah-modal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <form class="needs-validation" novalidate>
            @csrf
            <input type="hidden" name="category_id" value="{{ $category->id }}">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Tambah Album</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="album-tambah-title">Judul</label>
                        <input type="text" class="form-control" id="album-tambah-title" name="title" pattern="[A-Za-z0-9-_. ]+" required>
                        <small class="form-text text-muted">Karakter yang diperbolehkan adalah a-z, A-Z, 0-9, titik (.), underscore (_), tanda pisah (-), dan spasi</small>
                        <div class="invalid-feedback">
                            Data tidak boleh kosong
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                    <button type="submit" class="btn btn-primary">Tambah</button>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="modal fade" id="album-hapus-modal" tabindex="-1" role="dialog" aria-labelledby="album-hapus-modal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <form class="needs-validation" novalidate>
            @csrf
            <input type="hidden" name="id" id="album-hapus-id">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Hapus Album</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>
                        Apakah Anda yakin akan menghapus album <strong></strong>?. Menghapus album akan menghapus semua foto yang ada di dalamnya.
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-danger">Hapus</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection