routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'welcome');

Auth::routes(['register' => false]);

Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.', 'middleware' => ['auth']], function () {
    Route::redirect('/', '/dashboard/categories');
    Route::apiResource('categories', 'CategoryController')->except(['update']);
    Route::get('albums/categories', 'AlbumController@getByCategoryId')->name('albums.category');
    Route::apiResource('albums', 'AlbumController')->except(['update']);
    Route::post('images/regenerate/{albumId}', 'ImageController@regenerate')->name('images.regenerate');
    Route::apiResource('images', 'ImageController')->except(['update', 'show']);
});

app/Models/Album.php
<?php

namespace App\Models;

use App\Models\Category;
use App\Models\Image;
use Illuminate\Database\Eloquent\Model;

class Album extends Model
{
    protected $guarded = [];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function images()
    {
        return $this->hasMany(Image::class);
    }
}

app/Http/Controllers/AlbumController.php
<?php

namespace App\Http\Controllers;

use App\Repositories\AlbumRepositoryInterface;
use App\Repositories\CategoryRepositoryInterface;
use DataTables;
use Illuminate\Http\Request;
use Storage;

class AlbumController extends Controller
{
    private $albumRepository;
    private $categoryRepository;

    public function __construct(AlbumRepositoryInterface $albumRepository, CategoryRepositoryInterface $categoryRepository)
    {
        $this->albumRepository = $albumRepository;
        $this->categoryRepository = $categoryRepository;
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (! request()->ajax()) {
            $categories = $this->categoryRepository->getIdName();

            return view('dashboard.album.index', compact('categories'));
        }

        $albums = $this->albumRepository->index();

        return DataTables::of($albums)->make(true);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'title' => 'required|unique:albums|regex:/^[A-Za-z0-9._\s-]+$/',
            'category_id' => 'required|integer'
        ], [
            'regex' => 'Karakter yang diperbolehkan adalah a-z, A-Z, 0-9, titik (.), underscore (_), tanda pisah (-), dan spasi',
            'unique' => 'Nama sudah ada'
        ]);

        return $this->albumRepository->store($data);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $album = $this->albumRepository->firstOrFail($id);

        return view('dashboard.album.show', compact('album'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $album = $this->albumRepository->getPathAlbum($id);
        $isDeleted = $this->albumRepository->destroy($id);

        if ($isDeleted) {
            return Storage::deleteDirectory("$album->category_slug/$album->album_slug");
        }
    }

    public function getByCategoryId()
    {
        $albums = $this->albumRepository->getByCategoryId(request()->category_id);

        return DataTables::of($albums)->make(true);
    }
}

resources/views/dashboard/album/index.blade.php
@extends('layouts.sbAdmin2.app')

@section('title', 'Albums')

@section('head')
    <script src="{{ mix('js/dashboard/album/index.js') }}" defer></script>
@endsection

@section('content')
<!-- Page Heading -->
<h1 class="h3 mb-4 text-gray-800">Albums</h1>
<div class="row mb-2">
    <div class="col text-right">
        <button class="btn btn-primary" data-toggle="modal" data-target="#album-tambah-modal">Add Album</button>
    </div>
</div>
<div class="row">
    <div class="col">
        <div class="card shadow mb-4">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Title</th>
                                <th>Images</th>
                                <th>Category</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="album-tambah-modal" tabindex="-1" role="dialog" aria-labelledby="album-tambah-modal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <form class="needs-validation" novalidate>
            @csrf
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Tambah Album</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="album-tambah-title">Judul</label>
                        <input type="text" class="form-control" id="album-tambah-title" name="title" pattern="[A-Za-z0-9-_. ]+" required>
                        <small class="form-text text-muted">Karakter yang diperbolehkan adalah a-z, A-Z, 0-9, titik (.), underscore (_), tanda pisah (-), dan spasi</small>
                        <div class="invalid-feedback">
                            Data tidak boleh kosong
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="album-tambah-category">Kategori</label>
                        <select class="custom-select" id="album-tambah-category" name="category_id" required>
                            <option value="">Pilih Kategori</option>
                            @foreach ($categories as $item)
                            <option value="{{ $item->id }}">{{ $item->name }}</option>
                            @endforeach
                        </select>
                        <div class="invalid-feedback">
                            Data tidak boleh kosong
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                    <button type="submit" class="btn btn-primary">Tambah</button>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="modal fade" id="album-hapus-modal" tabindex="-1" role="dialog" aria-labelledby="album-hapus-modal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <form class="needs-validation" novalidate>
            @csrf
            <input type="hidden" name="id" id="album-hapus-id">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Hapus Album</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>
                        Apakah Anda yakin akan menghapus album <strong></strong>?. Menghapus album akan menghapus semua foto yang ada di dalamnya.
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-danger">Hapus</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/dashboard/album/show.blade.php
@extends('layouts.sbAdmin2.app')

@section('title', $album->title)

@section('head')
    <meta name="album-id" content="{{ $album->id }}">
    <script src="{{ mix('js/dashboard/album/show.js') }}" defer></script>
@endsection

@section('content')
<!-- Page Heading -->
<h1 class="h3 mb-4 text-gray-800">{{ $album->title }}</h1>
<div class="row mb-2">
    <div class="col text-left">
        <a href="{{ route('dashboard.albums.index') }}" class="btn btn-secondary btn-icon-split">
            <span class="icon text-white-50">
                <i class="fas fa-arrow-left"></i>
            </span>
            <span class="text">Back</span>
        </a>
    </div>
    <div class="col text-right">
        <button class="btn btn-primary" data-toggle="modal" data-target="#image-tambah-modal">Add Image</button>
        <button class="btn btn-warning" data-toggle="modal" data-target="#image-regenerate-modal">Regenerate URL</button>
    </div>
</div>
<div class="row">
    <div class="col">
        <div class="card shadow mb-4">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Image</th>
                                <th>Path</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="image-tambah-modal" tabindex="-1" role="dialog" aria-labelledby="image-tambah-modal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <form class="needs-validation" novalidate>
            @csrf
            <input type="hidden" name="album_id" value="{{ $album->id }}">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Tambah Gambar</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <label for="image-tambah-file">Choose Images</label>
                    <div class="custom-file mb-3">
                        <input type="file" name="image[]" class="custom-file-input" id="image-tambah-file" accept="image/*" multiple required>
                        <label class="custom-file-label" for="image-tambah-file">Choose images...</label>
                        <div class="invalid-feedback">
                            Data tidak boleh kosong
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                    <button type="submit" class="btn btn-primary">Tambah</button>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="modal fade" id="image-hapus-modal" tabindex="-1" role="dialog" aria-labelledby="image-hapus-modal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <form class="needs-validation" novalidate>
            @csrf
            <input type="hidden" name="id" id="image-hapus-id">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Hapus Gambar</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>
                        Apakah Anda yakin akan menghapus gambar <strong></strong>?
                    </p>
                    <div class="text-center">
                        <img src="" alt="thumbnail" class="img-thumbnail" height="125" width="200">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-danger">Hapus</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="modal fade" id="image-regenerate-modal" tabindex="-1" role="dialog" aria-labelledby="image-regenerate-modal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <form class="needs-validation" novalidate>
            @csrf
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Regenerate URL</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>
                        Apakah Anda yakin akan memperbarui semua URL di album <strong>{{ $album->title }}</strong>?
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-danger">Yakin</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection